dataset:
  path_pattern: "/Users/jeromebarre/AI/GEOS_CF_US/GEOS_CF_%Y%m%d_%H00z.nc4"
  norm_file: "/Users/jeromebarre/AI/ACORNN/moments/normalization_params_all.json"
  spatial_feature_file: "/Users/jeromebarre/AI/ACORNN/geometry/spatial_features_GEOS_CF_US.nc"
  radius: 1
  train_set:
    start_date: "2024-01-01"
    end_date: "2024-01-29"
    sample_ratio: 0.0015
    num_random_days: 200
  val_set:
    start_date: "2024-01-30"
    end_date: "2024-01-31"
    sample_ratio: 0.0005  # Smaller resample ratio for validation

training:
  max_epochs: 100
  batch_size: 10000
  learning_rate: 0.0005
  patience: 5
  stop_delta: 1e-4
  num_workers: 4
  validation_split: 0.0  # Not used since we use static val set
  resume_from_checkpoint: false
  checkpoint_path: "/Users/jeromebarre/AI/ACORNN/checkpoints/GEOS_CF_US_mlp_latest_test.pth"
  save_model_path: "/Users/jeromebarre/AI/ACORNN/checkpoints/GEOS_CF_US_mlp_weights_only.pth"

  #random_seed: 666 #for reproductibility
