# config_mlp_train.yaml

dataset:
  path_pattern: "/discover/nobackup/projects/jcsda/s2127/barre/GEOS_CF_US/output/GEOS_CF_%Y%m%d_%H00z.nc4"
  start_date: "2024-01-01 00:00"
  end_date: "2024-01-01 01:00"
  time_step_hours: 1
  norm_file: "/discover/nobackup/jbarre/jedidev/ACORNN/moments/normalization_params_all.json"
  radius: 1
  sample_ratio: 0.001

training:
  max_epochs: 100
  batch_size: 256
  learning_rate: 0.001
  patience: 10
  stop_delta: 1e-4
  validation_split: 0.1
  save_model_path: "trained_mlp.pth"
