dataset:
  path_pattern: "/discover/nobackup/projects/jcsda/s2127/barre/GEOS_CF_US/output/GEOS_CF_%Y%m%d_%H00z.nc4"
  norm_file: "/discover/nobackup/jbarre/jedidev/ACORNN/moments/normalization_params_all.json"
  spatial_feature_file: "/discover/nobackup/jbarre/jedidev/ACORNN/geometry/spatial_features_GEOS_CF_US.nc"
  radius: 1
  train_set:
    start_date: "2024-01-01"
    end_date: "2024-01-28"
    sample_ratio: 0.001
    num_random_days: 20
  val_set:
    start_date: "2024-01-29"
    end_date: "2024-01-30"
    sample_ratio: 0.001  # Smaller resample ratio for validation

training:
  max_epochs: 100
  batch_size: 256
  learning_rate: 0.0001
  patience: 10
  stop_delta: 1e-4
  num_workers: 0
  validation_split: 0.0  # Not used since we use static val set
  resume_from_checkpoint: false
  checkpoint_path: "/discover/nobackup/jbarre/jedidev/ACORNN/checkpoints/GEOS_CF_US_mlp_latest.pth"
  save_model_path: "/discover/nobackup/jbarre/jedidev/ACORNN/checkpoints/GEOS_CF_US_mlp_weights_only.pth"

  #random_seed: 666 #for reproductibility
